version: "3.8"
# Containers
services:
  rtorrent:
    image: binhex/arch-rtorrentvpn
    hostname: rtorrent
    container_name: rtorrent
    privileged: true
    restart: unless-stopped
    cap_add: 
      - NET_ADMIN
    environment:
      - STRICT_PORT_FORWARD=no
      - VPN_ENABLED=yes
      - VPN_USER=$VPN_USER
      - VPN_PASS=$VPN_PASS
      - VPN_PROV=$VPN_PROV
      - VPN_CLIENT=$VPN_CLIENT
      - ENABLE_PRIVOXY=yes
      - ENABLE_AUTODL_IRSSI=yes
      - ENABLE_RPC2=yes
      - ENABLE_RPC2_AUTH=yes
      - ENABLE_WEBUI_AUTH=yes
      - RPC2_USER=$RPC2_USER
      - RPC2_PASS=$RPC2_PASS
      - WEBUI_USER=$WEBUI_USER
      - WEBUI_PASS=$WEBUI_PASS
      - LAN_NETWORK=$LAN_NETWORK
      - VPN_INPUT_PORTS=9117
      - VPN_OUTPUT_PORTS=49184,6881
      - DEBUG=false
      - PHP_TZ=$PHP_TZ
      - UMASK=022
      - PUID=1000
      - PGID=1000
    networks: 
      - media
    ports:
      - 9080:9080
      - 9443:9443
      - 8118:8118
      - 49184:49184
      - 49184:49184/udp
      - 6881:6881
      - 6881:6881/udp
      - 5000:5000
    volumes:
      - $CONFIG_DIR/rtorrent:/config
      - $MEDIA_DIR:/media
      - /etc/localtime:/etc/localtime:ro

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$PHP_TZ
      - UMASK_SET=022
      - AUTO_UPDATE=true
    volumes:
      - $CONFIG_DIR/jackett:/config
    restart: unless-stopped
    networks:
      - media
    ports:
      - 9117:9117

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - $CONFIG_DIR/sonarr:/config
      - $MEDIA_DIR:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks: 
      - media

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    hostname: radarr
    networks: 
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$PHP_TZ
      - UMASK=022
    volumes:
      - $CONFIG_DIR/radarr:/config
      - $MEDIA_DIR:/media
    ports:
      - 7878:7878
    restart: unless-stopped

  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    container_name: ombi
    hostname: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$PHP_TZ
      - UMASK=022
    volumes:
      - $CONFIG_DIR/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    networks:
      - media

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$PHP_TZ
    volumes:
      - $CONFIG_DIR/tautulli:/config
    networks:
      - media
    ports:
      - 8181:8181
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=$PLEX_CLAIM
    networks: 
      - media
    ports:
      - 32400:32400
    volumes:
      - $CONFIG_DIR/plex:/config
      - $MEDIA_DIR:/media
    restart: unless-stopped

# Networks
networks:
  media:
    external:
      name: $DOCKER_NETWORK